name: CMake Build

on: [push]

env:
  BUILD_TYPE: Release
  CXX: g++-10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: sudo apt-get install g++-10
    
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.14.2
        
    - run: sudo apt-get install qtscript5-dev
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash

      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE
